[providers]
  [providers.file]
      directory = "/etc/traefik/sites-enabled"
      watch = true

  [providers.docker]
    exposedByDefault = false
    network = "web"
    endpoint = "tcp://socket-proxy:2375"
    # Swarm conf
    swarmMode = true
    swarmModeRefreshSeconds = 15  # default

[api]
  dashboard = true

[log]
  filePath = "/logs/traefik.log"
  level = "INFO"

[accessLog]
  filePath = "/logs/access.log"

[entryPoints]
  [entryPoints.web]
    address = ":80"

  [entryPoints.websecure]
    address = ":443"

[certificatesResolvers.leresolver.acme]
  email = "dev@pokestudio.it"
  storage = "/etc/traefik/acme.json"

  # Use staging for testing purposes.
  # caServer = "https://acme-staging-v02.api.letsencrypt.org/directory"

  [certificatesResolvers.leresolver.acme.httpChallenge]
    # used during the challenge
    entryPoint = "web"
